<div>
    <img src="images/emlyon.png" style="height:60px; float:left; padding-right:10px; margin-top:5px" />
    <span>
        <h1 style="padding-bottom:5px;"> AI Booster Week 01 - Python for Data Science </h1>
        <a href="https://masters.em-lyon.com/fr/msc-in-data-science-artificial-intelligence-strategy">[Emlyon]</a> MSc in Data Science & Artificial Intelligence Strategy (DSAIS) <br/>
         Paris | © Laureline PINAULT
    </span>
</div>

# Practice - 01: Basics of Python and Numpy
The bonus questions are to be skipped. If you have time left at the end of the session or at home you can try them.

---
### Objectives: 


*Gain familiarity with Python concepts and discover Numpy library by practice*

---

## Part 1: Let's write some functions!

__Exercise 1.__
Write a function called mul_table that takes as input a number and prints the multiplication table of that number.

In [23]:
def mul_table(n):
    for i in range(1, 11):
        print("{multiplier} * {multiplicand} = {multiplicantion}".format(
            multiplier=n, multiplicand=i, multiplicantion=n * i))

mul_table(9)

9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90


__Exercise 2.__
Write a function called prime_list that returns the list of prime factors of a number.

For example, the prime factors of 110 are 2, 5 and 11 and the prime factors of 56 are 2, 2, 2, 7.

In [20]:
def prime_list(n):
    result=[]
    for i in range(2,n+1):
        while n%i == 0:
            result.append(i)
            n = n//i
    return result

print(prime_list(110))
print(prime_list(56))

[2, 5, 11]
[2, 2, 2, 7]


__Exercise 3.__
Create a function called most_common_char that takes a string as a argument and the returns the most common character in that string. If there is an equality it should return the first on to appear in the string.

Tip: use a dictionnary.

In [40]:
def most_common_char(s):
    dict = {}
    for c in s:
        if c in dict.keys():
            dict[c] = dict[c]+1
        else:
            dict[c] = 1
    m = max(list(dict.values()))
    for c in dict.keys():
        if dict[c] == m:
            return c, m

most_common_char("bonjour")

('o', 2)

__Exercise 4.__
Write a function called is_valid_date that takes a date in string format DD/MM/YYYY and checks to see if it is a valid date and in the correct format.

In [54]:
def is_valid_date (date):
    if len(date) != 10:
        return False
    if date[2] != '/' or date[5] != '/':
        return False
    if not(date[0:2].isnumeric()) or not(date[3:5].isnumeric()) or not(date[6:11].isnumeric()):
        print(3)
        return False
    d = int(date[0:2])
    m = int(date[3:5])
    y = int(date[6:11])
    if d < 1 or d > 31 or m < 1 or m > 12:
        return False
    return True

print(is_valid_date("12/12/2059"))
print(is_valid_date("1/06/7896"))
print(is_valid_date("45/05/1997"))
print(is_valid_date("10/05/19a7"))

True
False
False
3
False


__Exercise (bonus).__
Create a function called encrypt that takes some text(String) and a Shift(Integer)and then encrypts the text using the Caesar Cipher algorithm, returning the encrypted text.

Create a second function to decrypt an encrypted string, using the same input parameters and returning the decrypted text.

See https://en.wikipedia.org/wiki/Caesar_cipher for more precisions

## Part 2: Numpy

In [4]:
import numpy as np

__Exercise 1.__
Create a 4X2 array of arbitrary unsigned int16 and prints its following attributes:
- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes.

In [8]:
array = np.empty([4,2], dtype = np.uint16) 
print("Printing Array:")
print(array)

print("Printing numpy array Attributes")
print("Array Shape is: ", array.shape)
print("Array dimensions are ", array.ndim)
print("Length of each element of array in bytes is ", array.itemsize)

Printing Array:
[[ 7391 38943]
 [58673 54643]
 [20777 39895]
 [19488   878]]
Printing numpy array Attributes
Array Shape is:  (4, 2)
Array dimensions are  2
Length of each element of array in bytes is  2


__Exercise 2.__ 
Create a 5X2 integer array from a range between 200 to 400 such that the difference between each element is 20
(tip: think about the reshape() function).

In [32]:
sampleArray = np.arange(200, 400, 20)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

[[200 220]
 [240 260]
 [280 300]
 [320 340]
 [360 380]]


__Exercise 3.__
Following is the provided numPy array. Return array of items by taking the second column from all rows. Print it.

In [33]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Input Array:")
print(sampleArray)

print("\nPrinting array of items in the third column from all rows:")
newArray = sampleArray[:,1]
print(newArray)


Input Array:
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Printing array of items in the third column from all rows:
[22 55 88]


__Exercise 4.__
Following is the provided numPy array. Return array of odd rows and even columns. Print it.

In [31]:
sampleArray = np.array([[3 ,9, 9, 12], [16 ,18, 231, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 58], [51 ,54, 57, 61]]) 
print("Input Array:")
print(sampleArray)

print("\nPrinting array of odd rows and even columns:")
newArray = sampleArray[::2, 1::2]
print(newArray)

Input Array:
[[  3   9   9  12]
 [ 16  18 231  24]
 [ 27  30  33  36]
 [ 39  42  45  58]
 [ 51  54  57  61]]

Printing array of odd rows and even columns:
[[ 9 12]
 [30 36]
 [54 61]]


__Exercise 5.__
Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element. Print the resulting array at each step.

In [30]:
array1 = np.array([[2, 6, 5], [2 ,4, 27]])
array2 = np.array([[13 ,0, 3], [16 ,7, 1]])

print("Input Arrays:")
print(array1)
print(array2)

resultArray  = array1 + array2
print("\nAddition of two arrays is:")
print(resultArray)

print("\nResult array after calculating square of all elements:")
resultArray = resultArray ** 2
print(resultArray)


Input Array:
[[ 2  6  5]
 [ 2  4 27]]
[[13  0  3]
 [16  7  1]]

Addition of two arrays is:
[[15  6  8]
 [18 11 28]]

Result array after calculating square of all elements:
[[225  36  64]
 [324 121 784]]


__Exercise 6.__
Create an 8X5 integer array from a range starting at -20 and such that the difference between each element is 2 and then split the array into four equal-sized sub-arrays.

In [27]:
sampleArray = np.arange(-20, 60, 2)
sampleArray = sampleArray.reshape(8,5)
print (sampleArray)

subArrays = numpy.split(sampleArray, 4) 
print(subArrays)

[[-20 -18 -16 -14 -12]
 [-10  -8  -6  -4  -2]
 [  0   2   4   6   8]
 [ 10  12  14  16  18]
 [ 20  22  24  26  28]
 [ 30  32  34  36  38]
 [ 40  42  44  46  48]
 [ 50  52  54  56  58]]
[array([[-20, -18, -16, -14, -12],
       [-10,  -8,  -6,  -4,  -2]]), array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]]), array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]]), array([[40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])]


__Exercise 7.__
Following is the provided numPy array. Sort it by its third row and then by its second column.

In [34]:
print("Input array:")
sampleArray = np.array([[54,3,723],[85,21,1],[56,54,66]]) 
print (sampleArray)

sortArrayByRow = sampleArray[:,sampleArray[2,:].argsort()]
print("\nSorting Original array by third row:")
print(sortArrayByRow)

print("\nSorting Original array by second column:")

sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
print(sortArrayByColumn)



Input array:
[[ 54   3 723]
 [ 85  21   1]
 [ 56  54  66]]

Sorting Original array by third row:
[[  3  54 723]
 [ 21  85   1]
 [ 54  56  66]]

Sorting Original array by second column:
[[ 54   3 723]
 [ 85  21   1]
 [ 56  54  66]]


__Exercise 9.__
Following is the provided numPy array. 
Delete the second column from it and insert the following new column in its place.

In [35]:
sampleArray = np.array([[34,3,93],[2,52,12],[4,5,86]]) 
newColumn = np.array([[9,8,7]])

print("Array after deleting column 2 on axis 1:")
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = numpy.array([[10,10,10]])

print("\nArray after inserting column 2 on axis 1:")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Array after deleting column 2 on axis 1:
[[34 93]
 [ 2 12]
 [ 4 86]]

Array after inserting column 2 on axis 1:
[[34 10 93]
 [ 2 10 12]
 [ 4 10 86]]
